### ISSUE TITLE
WalletConnect hanging

### ISSUE THREAD

**Issue by williammortondev** [terra-money/wallet-provider#18]
Hi,

Just testing out the create react app sample 
Working well with Chrome extension connect, but with the wallet connect with mobile station app I get "ready to connect" screen hanging indefinitely .

Is this a known issue?

**Comment by iamssen** [comment]
@williammortondev It's because SSL is not set. (SSL setting is required during development because walletconnect communicates with https / wss) template is as simple as possible, so SSL setting was not enforced.

Please refer to the links below.

- You need to set local Root CA configuration: <https://github.com/FiloSottile/mkcert>
- Also you have to set Root CA to your mobile device: <https://github.com/FiloSottile/mkcert#mobile-devices>
- And set the cert files to react-scripts : <https://github.com/terra-money/wallet-provider/blob/main/packages/package.json#L7>
- <https://create-react-app.dev/docs/using-https-in-development/>

**Comment by iamssen** [comment]
There may be the same problem after the above settings. It happens when the Walletconnect development server is in bad condition and not responding properly.

Then replace the bridge server as shown below.

```
<WalletProvider
      connectorOpts={{ bridge: 'https://tequila-walletconnect.terra.dev/'}}
      ...
    >
```
