### ISSUE TITLE
docs for interfacing with extension?

### ISSUE THREAD

**Issue by dakom** [terra-money/wallet-provider#22]
The "non-react" examples here all bundle react, and ultimately the codebase here adds a lot to a non-react project!

I realize it might be a bit too much to ask for a more framework-agnostic refactor, but is there documentation somewhere to show how to do only the extension-interface flow?

I'd imagine that it doesn't use its own UI, just that of the extension, and should be able to do more cleanly?

(as an aside - I couldn't get the provider to build in rollup at all)

**Comment by iamssen** [comment]
@dakom Since the goal of [the sample](https://github.com/terra-money/wallet-provider/blob/main/templates/wallet-controller/README.md#this-template-is-just-for-reference) is to explain the behavior of `WalletController`, I just used `react-scripts` without creating a separate lightweight `webpack` setting. 

Since the primary goal of this project is to provide multiple interfaces (Extension, Walletconnect...) as a common simple interface, no separate interface is provided for Extension alone.

However, if you want, you can compose [`@terra-dev/chrome-extension`](https://www.npmjs.com/package/@terra-dev/chrome-extension) and [`@terra-dev/use-wallet`](https://www.npmjs.com/package/@terra-dev/use-wallet) to create a new React Context that can be used instead of `<WalletProvider>`. (or you can only use `@terra-dev/chrome-extension` if you don't use React)

I want to provide documents for these sub-packages, but I haven't been able to provide them yet because other projects are underway together. I think this can be provided in the future.

This project is not using rollup. If you want to understand how it is built, run `yarn workspace packages run build` and you'll see that the `~/packages/out/packages` directory is created. Please refer to these links.

- <https://www.npmjs.com/package/rocket-punch>
- <https://github.com/terra-money/wallet-provider/blob/main/packages/.packages.json>

**Comment by dakom** [comment]
Closing this issue for now... I was able to just work around this by putting the wallet provider in a separate iframe 😅
