### ISSUE TITLE
Vue.js Support

### ISSUE THREAD

**Issue by phips28** [terra-money/wallet-provider#32]
Is there support for Vue.js in the future? Or should I just copy paste the relevant files into my project?

**Comment by iamssen** [comment]
@phips28 You're right. Some internal components are still using react. They are usually functions such as modal. https://github.com/terra-money/wallet-provider/blob/main/packages/src/%40terra-dev/walletconnect-qrcode-modal/index.tsx

In order to remove it, I think we need to change some components that are used internally to technologies that do not require running time. (For example, web-component or svelte)

I think I will eliminate unnecessary react internal dependence in the near future. It may be inconvenient to include unnecessary dependence, but please understand for the time being. This change may be delayed a little because there are many projects currently underway.

We can eliminate react dependence in many ways, but I want this change as possible to be made in a way that does not create much maintenance burden afterwards. I'll think about this in a better way.

**Comment by iamssen** [comment]
I wanted to include this in this major update `@3.0.0`, but unfortunately I couldn't. It seems that it will take more time to change React to optional dependency.

**Comment by iamssen** [comment]
https://github.com/terra-money/wallet-provider/releases/tag/v3.2.0
