### ISSUE TITLE
[Next.js] Uncaught SyntaxError: Unexpected template string  

### ISSUE THREAD

**Issue by jmsaulnier** [terra-money/wallet-provider#45]
After updating packages dependencies to:
```
@terra-money/terra.js": "^3.0.1",
@terra-money/wallet-provider": "^3.1.0",
```

I'm getting an error `Uncaught SyntaxError: Unexpected template string` (It seems to be from:  
 **\`sha${Bg}\`** ) after running `npm run export`. This error is only visible on **production**

------

**Temporary solution:**

Set `swcMinify: false` in `next.config.js`

-------
So I'm not sure if this issue is coming from the new compiler `swcMinify` from `next.js` or we could avoid this error by using a different syntax somewhere?

**Comment by iamssen** [comment]
@jmsaulnier I will check. thank you for reporting.

**Comment by jmsaulnier** [comment]
@iamssen Thank you for your awesome work 🙏

**Comment by iamssen** [comment]
@jmsaulnier After updating the template to the latest version of `next@12.0.4`, I succeeded without any problems with the `next build && next export` command.

It is thought that this error does not occur in the source code compile of the `wallet-provider`. You should check the other libraries you import.

You would use a lot of libraries in the context of developing block-chain, but block-chain libraries are a little clumsy in their management. Since it usually relies on the webpack's node polyfill, problems can arise in `swc` or `esbuild` that support only the latest js specifications such as esmodule.
