### ISSUE TITLE
Is there any package which is not tightly coupled with React ?

### ISSUE THREAD

**Issue by Stradivario** [terra-money/wallet-provider#46]
Hello there!

Great job for the Good work for the Wallet provider!

I am not a React user and i prefer to use WebComponents instead or pure JS is there any Generic version of the wallet provider for there compatible with different frameworks ?

Since i want to implement it with framework that i build based on Lit Html with this starter https://github.com/rxdi/starter-client-side-lit-html

I am trying to reverse engineer this code but it looks like really tightly coupled with React Hooks and it is not easily extendable for other platforms even using it with pure JS is a pure nightmare.

Any ideas how to accomplish my idea ?

I will try to replicate everything here in order to make it work more generic but i am not sure when this will happen so this is why i am asking if someone have something in mind.

Cheers!

**Comment by iamssen** [comment]
@Stradivario https://github.com/terra-money/wallet-provider/tree/main/templates/wallet-controller

Please refer to this link.

`class WalletController`, the bottom part of the `wallet-provider`, was created based on RxJs, and React APIs such as `useWallet()` bind it.

`WalletController` can be used directly if you want. However, it will not be as convenient as the React API.

However, since internal parts such as Model still use React, it is still necessary to add package.json dependencies for React. (I will then work on removing React from internally)

**Comment by Stradivario** [comment]
I check the code and i saw that here https://github.com/terra-money/wallet-provider/blob/main/packages/src/%40terra-money/wallet-provider/index.ts#L3 

We are exporting `./impl-react` and `@terra-money/use-wallet` which are libraries using react

So if i don't install react i will get the error 'react-dom' or 'react' cannot be found in dependency resolution.

Even if i install react i will get an error that i don't use the correct way react

```
Uncaught (in promise) Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476)
    at useContext (react.development.js:1484)
    at useWallet (useWallet.ts:374)
    at TerraProvider.<anonymous> (terra.provider.ts:72)
    at Generator.next (<anonymous>)
    at terra.provider.ts:4
    at new Promise (<anonymous>)
    at __awaiter (terra.provider.ts:4)
    at TerraProvider.OnInit (terra.provider.ts:62)
    at ContainerInstance.getServiceValue (ContainerInstance.js:244)
    ```
    
    So there is a big problem using it with other libraries or native.
    
I will write down a few things today and i will let you know if i can remove every usage of react and leave the core logic untouched. After that we can just connect the react with the generic controller.

Cheers and thanks for the fast response!

**Comment by iamssen** [comment]
@Stradivario Is this an error when you only use `WalletController`?

I will check this error tomorrow.

Unfortunately, it still needs to install `react`, `react-dom`, and `styled-components` in your `dependencies`. The reason why React exists in multiple copies may be because `node_modules` is not flat. (If you add `react`, `react-dom`, and `styled-components` to your `dependencies` and the problem continues, try `npm deadupe` or `yarn dedupe`)

Anyway, I'll look into this tomorrow.

**Comment by iamssen** [comment]
https://github.com/terra-money/wallet-provider/pull/48

I separated the `WalletController` into a separate package. This no longer requires dependence such as `react`.

I am not going to change the API, so if possible, I would like you to install this alpha version and test it together.

**Comment by iamssen** [comment]
https://github.com/terra-money/wallet-provider/releases/tag/v3.2.0

**Comment by Stradivario** [comment]
Hey @iamssen thanks for the effort doing these changes!

I will try it out today and will write down how the things are going.

I am sorry for the late reply but i am having some production deployments and i don't have much time to test this out.

Cheers!
