### ISSUE TITLE
`signBytes` on mobile

### ISSUE THREAD

**Issue by Ruborcalor** [terra-money/wallet-provider#50]
Will `signBytes` ever be supported on mobile, or will it only ever be supported by the terra station chrome extension?

**Comment by tk-o** [comment]
Isn't the Terra Station mobile app required on mobile? Chrome extension seems only to work for Chrome Desktop.

**Comment by iamssen** [comment]
`sign()` and `signBytes()` does not support on Terra station mobile (= wallet connect)

Extension has all actions performed locally, but wallet connect is connected through multiple servers in the middle. We don't support it because we think there can be problems with the operation of `sign()` and `signBytes()`.
